# PostgreSQL datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/todo

# Hibernate ORM & schema
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Swagger UI (OpenAPI UI)
quarkus.swagger-ui.path=/q/swagger-ui
quarkus.swagger-ui.always-include=true

# JWT Security
quarkus.smallrye-jwt.enabled=true

# JWT issuer for token verification (must match in JwtGenerator)
smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*
mp.jwt.verify.issuer=todo-app

#Python service
quarkus.rest-client.nlp-service.url=http://localhost:8000
quarkus.rest-client.nlp-service.scope=jakarta.inject.Singleton